apiVersion: v1
kind: Service
metadata:
  name: ikik7t8j6ruj
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ikik7t8j6ruj"
    port: 8080
  selector:
    app: ikik7t8j6ruj
